version: 2

updates:
  - package-ecosystem: npm
    directory: /
    groups:
      oxc:
        patterns:
          - 'oxlint'
          - 'oxlint-tsgolint'
          - 'oxfmt'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - '유형:자동수정'
    schedule:
      interval: weekly
      day: monday
      time: '04:30'
      timezone: Asia/Seoul

  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/setup
      - /.github/actions/codeql
    groups:
      codeql:
        patterns:
          - 'github/codeql-action/*'
      actions-cache:
        patterns:
          - 'actions/cache'
          - 'actions/cache/*'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - '유형:자동수정'
    schedule:
      interval: weekly
      day: monday
      time: '04:30'
      timezone: Asia/Seoul
