allowBuilds:
  '@google/genai': true
  protobufjs: true
  simple-git-hooks: true

savePrefix: ''

catalog:
  '@ag-ui/core': 0.0.59
  '@anthropic-ai/sdk': 0.126.0
  '@google/genai': 2.22.0
  '@types/node': 24.13.4
  '@standard-schema/spec': 1.1.0
  cordis: 4.0.0-rc.10
  openai: 7.15.0
  tsdown: 0.23.0
  typescript: 6.0.3
  vitest: 5.0.1

packages:
  - apps/*
  - examples/*
  - packages/*
  - tools/*
